const STRINGS = {
  fr: {
    // Nav
    nav_analyse: "Accueil",
    nav_historique: "Versions",
    nav_chat: "Chat",
    nav_reglages: "Réglages",
    nav_profil: "Profil",
    nav_back: "Retour",
    // Login
    login_title: "SE CONNECTER",
    signup_title: "CRÉER MON COMPTE",
    login_tab: "Se connecter",
    signup_tab: "Créer un compte",
    google: "Continuer avec Google",
    apple: "Continuer avec Apple",
    facebook: "Continuer avec Facebook",
    or_email: "ou par email",
    email: "Email",
    password: "Mot de passe",
    forgot: "Mot de passe oublié ?",
    cgu: "En continuant, tu acceptes les",
    cgu2: "Conditions d'utilisation",
    cgu3: "et la",
    cgu4: "Politique de confidentialité",
    // Home
    tagline: "Versioning de productions audio",
    mode_ref_label: "TITRE DE RÉFÉRENCE",
    mode_ref_sub: "Upload un titre qui t'inspire",
    mode_ref_desc:
      "Analyse une production existante — éléments sonores, chaîne de traitement, plugins probables.",
    mode_perso_label: "MA PROD MUSICALE",
    mode_perso_sub: "Upload ton propre mix",
    mode_perso_desc:
      "Analyse ta propre prod pour un diagnostic complet — points forts, lacunes, plan d'action.",
    mode_ask_label: "POSER UNE QUESTION",
    mode_ask_sub: "L'IA Versions te répond",
    mode_ask_desc:
      "Pose directement une question sur la prod, le mixage, un plugin ou une technique.",
    // Input
    source_ref: "SOURCE À DÉCODER",
    source_perso: "TA PRODUCTION",
    source_ref_sub: "Colle le lien de la prod qui t'inspire, ou uploade le fichier audio.",
    source_perso_sub: "Uploade ton mix ou colle un lien de partage privé.",
    tab_link: "Lien",
    tab_upload: "Upload",
    url_placeholder: "Colle un lien Spotify, YouTube, SoundCloud…",
    daw_label: "Ton DAW",
    daw_placeholder: "Sélectionne ton DAW",
    analyze_btn: "ANALYSER",
    analyze_btn_perso: "DIAGNOSTIQUER",
    complete_fields: "Compléter les champs",
    source_audio: "SOURCE AUDIO",
    ton_daw: "TON DAW",
    mode_ref_badge: "MODE RÉFÉRENCE",
    mode_perso_badge: "MODE PERSONNEL",
    // Fiche tabs
    tab_elements: "ANALYSE",
    tab_elements_perso: "DIAGNOSTIC",
    tab_ecoute: "ÉCOUTE",
    tab_ecoute_perso: "RESSENTI",
    tab_chain: "CHAÎNE PROBABLE",
    tab_chain_perso: "PROBLÈMES IDENTIFIÉS",
    tab_plugins: "PLUGINS IDENTIFIÉS",
    tab_plugins_perso: "OUTILS RECOMMANDÉS",
    tab_tips: "REPRODUIRE",
    tab_tips_perso: "PLAN D'ACTION",
    generating: "Génération…",
    kb_active: "Base de connaissance active",
    click_to_dig: "Cliquer sur un élément pour approfondir",
    // Ask modal
    ask_title: "POSER UNE QUESTION",
    ask_sub: "Expert production musicale · Tous DAWs",
    ask_placeholder: "Ta question…",
    // Historique
    historique_title: "HISTORIQUE",
    historique_sub: "Tes analyses précédentes",
    search_placeholder: "Rechercher un titre, un artiste, un DAW…",
    filter_all: "Toutes",
    filter_ref: "Référence",
    filter_perso: "Personnel",
    no_results: "Aucun résultat",
    no_results_sub: "Essaie un autre terme ou réinitialise les filtres",
    reset: "Réinitialiser",
    // Réglages
    reglages_title: "RÉGLAGES",
    section_profil: "Profil",
    section_abonnement: "Abonnement",
    section_paiement: "Paiement",
    section_preferences: "Préférences",
    section_securite: "Sécurité",
    section_donnees: "Données",
    plan_current: "PLAN ACTUEL",
    upgrade_btn: "PASSER EN PRO",
    save_btn: "ENREGISTRER",
    modify_btn: "MODIFIER",
    free_plan: "5 analyses / mois",
    pro_features:
      "Analyses illimitées · Export PDF · Assistant enrichi · Historique complet",
    daw_default: "DAW PAR DÉFAUT",
    lang_label: "LANGUE",
    notif_news: "Notifications — Nouveautés",
    danger_zone: "Zone de danger",
    delete_account: "Supprimer mon compte",
    export_analyses: "Exporter mes analyses",
    export_analyses_desc: "Télécharger toutes tes fiches en PDF",
    export_data: "Exporter mes données",
    export_data_desc: "Archive complète au format JSON",
    delete_data: "Supprimer toutes mes données",
    // Menu
    username_label: "Nom d'utilisateur",
    change_photo: "Changer la photo",
    no_card: "Aucune carte enregistrée",
    card_required: "Requis pour le plan Pro",
    add_card: "Ajouter une carte",
    irrev: "{ls.irrev}",
    menu_account: "Mon compte",
    menu_premium: "Passer en Premium",
    menu_settings: "Réglages",
    menu_help: "Aide & support",
    menu_logout: "Se déconnecter",
    // Confidence
    conf_measured: "MESURÉ",
    conf_identified: "IDENTIFIÉ",
    conf_suggested: "SUGGÉRÉ",
  },
  en: {
    // Nav
    nav_analyse: "Home",
    nav_historique: "Versions",
    nav_chat: "Chat",
    nav_reglages: "Settings",
    nav_profil: "Profile",
    nav_back: "Back",
    // Login
    login_title: "SIGN IN",
    signup_title: "SIGN UP",
    login_tab: "Sign in",
    signup_tab: "Sign up",
    google: "Continue with Google",
    apple: "Continue with Apple",
    facebook: "Continue with Facebook",
    or_email: "or with email",
    email: "Email",
    password: "Password",
    forgot: "Forgot password?",
    cgu: "By continuing, you agree to our",
    cgu2: "Terms of Service",
    cgu3: "and",
    cgu4: "Privacy Policy",
    // Home
    tagline: "Audio production versioning",
    mode_ref_label: "REFERENCE TRACK",
    mode_ref_sub: "Upload a track that inspires you",
    mode_ref_desc:
      "Analyse an existing production — sonic elements, processing chain, probable plugins.",
    mode_perso_label: "MY PRODUCTION",
    mode_perso_sub: "Upload your own mix",
    mode_perso_desc:
      "Analyse your own track for a full diagnostic — strengths, weaknesses, action plan.",
    mode_ask_label: "ASK A QUESTION",
    mode_ask_sub: "Versions AI answers you",
    mode_ask_desc:
      "Ask directly about production, mixing, a plugin or a technique.",
    // Input
    source_ref: "SOURCE TO ANALYSE",
    source_perso: "YOUR PRODUCTION",
    source_ref_sub: "Paste a link to the track that inspires you, or upload the audio file.",
    source_perso_sub: "Upload your mix or paste a private share link.",
    tab_link: "Link",
    tab_upload: "Upload",
    url_placeholder: "Paste a Spotify, YouTube, SoundCloud link…",
    daw_label: "Your DAW",
    daw_placeholder: "Select your DAW",
    analyze_btn: "ANALYSE",
    analyze_btn_perso: "DIAGNOSE",
    complete_fields: "Complete the fields",
    source_audio: "SOURCE AUDIO",
    ton_daw: "YOUR DAW",
    mode_ref_badge: "REFERENCE MODE",
    mode_perso_badge: "PERSONAL MODE",
    // Fiche tabs
    tab_elements: "ANALYSIS",
    tab_elements_perso: "DIAGNOSTIC",
    tab_ecoute: "LISTENING",
    tab_ecoute_perso: "FEELING",
    tab_chain: "PROBABLE CHAIN",
    tab_chain_perso: "ISSUES FOUND",
    tab_plugins: "PLUGINS IDENTIFIED",
    tab_plugins_perso: "RECOMMENDED TOOLS",
    tab_tips: "REPRODUCE",
    tab_tips_perso: "ACTION PLAN",
    generating: "Generating…",
    kb_active: "Knowledge base active",
    click_to_dig: "Click an element to dig deeper",
    // Ask modal
    ask_title: "ASK ANY QUESTION",
    ask_sub: "Music production expert · All DAWs",
    ask_placeholder: "Your question…",
    // Historique
    historique_title: "HISTORY",
    historique_sub: "Your previous analyses",
    search_placeholder: "Search by title, artist, DAW…",
    filter_all: "All",
    filter_ref: "Reference",
    filter_perso: "Personal",
    no_results: "No results",
    no_results_sub: "Try different terms or reset filters",
    reset: "Reset",
    // Réglages
    reglages_title: "SETTINGS",
    section_profil: "Profile",
    section_abonnement: "Subscription",
    section_paiement: "Payment",
    section_preferences: "Preferences",
    section_securite: "Security",
    section_donnees: "Data",
    plan_current: "CURRENT PLAN",
    upgrade_btn: "GO PRO",
    save_btn: "SAVE",
    modify_btn: "UPDATE",
    free_plan: "5 analyses / month",
    pro_features:
      "Unlimited analyses · PDF export · Enhanced assistant · Full history",
    daw_default: "DEFAULT DAW",
    lang_label: "LANGUAGE",
    notif_news: "Notifications — News & updates",
    danger_zone: "Danger zone",
    delete_account: "Delete my account",
    export_analyses: "Export my analyses",
    export_analyses_desc: "Download all your reports as PDF",
    export_data: "Export my data",
    export_data_desc: "Full archive in JSON format",
    delete_data: "Delete all my data",
    // Menu
    username_label: "Username",
    change_photo: "Change photo",
    no_card: "No card on file",
    card_required: "Required for Pro plan",
    add_card: "Add a card",
    irrev: "This action is irreversible. All your analyses and preferences will be deleted.",
    menu_account: "My account",
    menu_premium: "Go Premium",
    menu_settings: "Settings",
    menu_help: "Help & support",
    menu_logout: "Sign out",
    // Confidence
    conf_measured: "MEASURED",
    conf_identified: "IDENTIFIED",
    conf_suggested: "SUGGESTED",
  },
};

export default STRINGS;
