/* ============================================================
 * VERSIONS — Dictionnaire i18n FR / EN
 * ------------------------------------------------------------
 * Organisation : clés groupées par namespace (common, nav,
 * auth, home, input, loading, fiche, versions, reglages,
 * modals, sidebar, player, chat, errors, datetime…).
 * ------------------------------------------------------------
 * Les noms de projets, titres, artistes saisis par l'utilisateur
 * ne sont PAS des clés de traduction — ils restent bruts.
 * ============================================================ */

const STRINGS = {
  fr: {
    /* ─────────────────────────── COMMUN ────────────────────── */
    common: {
      loading: "CHARGEMENT...",
      save: "Enregistrer",
      saving: "Enregistrement...",
      saved: "✓ Enregistré",
      cancel: "Annuler",
      delete: "Supprimer",
      rename: "Renommer",
      create: "Créer",
      close: "Fermer",
      confirm: "Confirmer",
      ok: "OK",
      back: "Retour",
      continue: "Continuer",
      next: "Suivant",
      prev: "Précédent",
      yes: "Oui",
      no: "Non",
      search: "Rechercher",
      reset: "Réinitialiser",
      tryAgain: "Réessayer",
      optional: "(optionnel)",
      required: "Obligatoire",
      copy: "Copier",
      copied: "Copié !",
      share: "Partager",
      edit: "Modifier",
      add: "Ajouter",
      or: "ou",
      of: "sur",
      and: "et",
      by: "par",
      to: "à",
      from: "depuis",
      all: "Tous",
      none: "Aucun",
      unknown: "Inconnu",
      untitled: "Sans titre",
      untitledMale: "Sans nom",
      pending: "En attente",
      inProgress: "En cours",
      done: "Terminé",
      more: "Plus",
      less: "Moins",
      showMore: "Voir plus",
      showLess: "Voir moins",
      viewDetails: "Voir les détails",
      hide: "Masquer",
      show: "Afficher",
      new: "Nouveau",
      newFem: "Nouvelle",
      processing: "Traitement…",
      generating: "Génération…",
      analysing: "Analyse en cours…",
      track: "titre",
      tracks: "titres",
      version: "version",
      versions: "versions",
      project: "projet",
      projects: "projets",
    },

    /* ─────────────────────────── NAV ───────────────────────── */
    nav: {
      home: "Accueil",
      versions: "Versions",
      chat: "Chat",
      reglages: "Réglages",
      profile: "Profil",
      back: "Retour",
      newAnalysis: "Nouvelle analyse",
    },

    /* ─────────────────────────── BRAND ─────────────────────── */
    brand: {
      tagline: "Versioning de productions audio",
      taglineAction: "Analyse · Compare · Évolue",
    },

    /* ─────────────────────────── AUTH ──────────────────────── */
    auth: {
      signInTitle: "SE CONNECTER",
      signUpTitle: "CRÉER MON COMPTE",
      signInTab: "Se connecter",
      signUpTab: "Créer un compte",
      signIn: "Se connecter",
      signUp: "S'inscrire",
      signOut: "Se déconnecter",
      google: "Continuer avec Google",
      apple: "Continuer avec Apple",
      facebook: "Continuer avec Facebook",
      or: "OU",
      orEmail: "ou par email",
      email: "Email",
      password: "Mot de passe",
      forgotPassword: "Mot de passe oublié ?",
      confirmEmail: "Vérifiez votre email pour confirmer votre compte.",
      noAccount: "Pas de compte ? S'inscrire",
      alreadyRegistered: "Déjà inscrit ? Se connecter",
      cgu1: "En continuant, tu acceptes les",
      cgu2: "Conditions d'utilisation",
      cgu3: "et la",
      cgu4: "Politique de confidentialité",
    },

    /* ─────────────────────────── HOME / WELCOME ────────────── */
    home: {
      greeting: "SALUT !",
      greetingWithName: "SALUT {name} !",
      newTrack: "Nouveau titre",
      newVersion: "Ajouter une version",
      pickTrack: "À quel titre ?",
      myTracks: "Mes",
      myTracksAccent: "titres",
      empty: "Importe ton premier titre pour commencer l'aventure.",
      tipLabel: "Le saviez-vous",
      ctaAnalysis: "Analyse",
      playing: "En lecture",
      play: "Écouter",
      pause: "Pause",
      tips: [
        "Faire des pauses régulières permet de conserver une écoute attentive et objective.",
        "Tes oreilles se fatiguent après 45 min — une pause de 10 min te fait gagner 2h de travail.",
        "Écouter ton mix dans un autre contexte (voiture, écouteurs) révèle ce que le studio cache.",
        "Baisser le volume de monitoring aide à repérer les déséquilibres de balance.",
        "Prendre du recul sur un mix pendant 24h change complètement ta perception.",
        "Comparer régulièrement avec une référence recalibre ton oreille et tes choix.",
        "Le silence entre les sessions est aussi important que le travail lui-même.",
        "Écouter à faible volume est le meilleur test : si le mix fonctionne bas, il fonctionnera fort.",
      ],
    },

    /* ─────────────────────────── INPUT ─────────────────────── */
    input: {
      title: "NOUVELLE ANALYSE",
      tagline: "Analyse · Compare · Évolue",
      sectionMix: "TON MIX",
      sectionVocalType: "TYPE DE TITRE",
      sectionProject: "PROJET",
      sectionTitle: "TITRE",
      sectionVersion: "VERSION",
      sectionDaw: "TON DAW",
      titlePlaceholder: "Nom du morceau",
      versionPlaceholder: "ex: Mix v3, Demo, Master…",
      dawPlaceholder: "Sélectionne ton DAW…",
      dropText: "Glisser le fichier ici ou cliquer",
      dropFormats: "WAV · AIFF · MP3 · FLAC — 200 MB max",
      vocalSung: "Chanté",
      vocalInstrumental: "Instrumental",
      vocalVoiceQuestion: "VOIX SUR CE TITRE ?",
      vocalComing: "À venir",
      vocalFinal: "Instrumental définitif",
      vocalComingTip: "Tu prévois d'ajouter des voix sur une prochaine version",
      vocalFinalTip: "Œuvre purement instrumentale, pas de voix prévue",
      vocalHintIdle: "Ce choix évite que l'absence de voix soit notée comme un défaut à tort.",
      vocalHintComing: "L'analyse traitera la voix comme une étape à franchir.",
      vocalHintFinal: "La section voix sera ignorée dans l'analyse et le score.",
      projectPickerFirst: "+ Crée ton premier projet",
      projectPickerNew: "+ Nouveau projet",
      projectLocked: "Projet verrouillé — ce titre est déjà rattaché à un projet",
      projectLockedHint: "Projet verrouillé — ce titre appartient déjà à ce projet.",
      analyze: "Analyser",
      fieldsRemaining: "{filled}/{total} champs remplis",
      newProjectTitle: "Nouveau projet",
      newProjectPlaceholder: "Nom du projet",
    },

    /* ─────────────────────────── LOADING ───────────────────── */
    loading: {
      title: "ANALYSE EN COURS",
      sub: "Ton mix est en train d'être décortiqué.",
      cancel: "Annuler l'analyse",
      stepUpload: "Envoi du fichier",
      stepListen: "Écoute qualitative",
      stepExtract: "Extraction des éléments",
      stepDetectVocal: "Détection vocale",
      stepBuildFiche: "Construction de la fiche",
      stepSynthesis: "Synthèse finale",
      stageListening: "Gemini écoute ton morceau…",
      stageAnalyzing: "Claude rédige le diagnostic…",
      stageRag: "Croisement avec la base PureMix…",
      stageFinal: "Dernière relecture…",
      errorTitle: "L'analyse a échoué",
      errorRetry: "Réessayer",
      errorBack: "Revenir en arrière",
    },

    /* ─────────────────────────── FICHE ─────────────────────── */
    fiche: {
      headerBadgeRef: "MODE RÉFÉRENCE",
      headerBadgePerso: "MODE PERSONNEL",
      headerVerdict: "VERDICT",
      headerScore: "SCORE",
      tabAnalysis: "ANALYSE",
      tabAnalysisPerso: "DIAGNOSTIC",
      tabListen: "ÉCOUTE",
      tabListenPerso: "RESSENTI",
      tabChain: "CHAÎNE PROBABLE",
      tabChainPerso: "PROBLÈMES IDENTIFIÉS",
      tabPlugins: "PLUGINS IDENTIFIÉS",
      tabPluginsPerso: "OUTILS RECOMMANDÉS",
      tabReproduce: "REPRODUIRE",
      tabActionPlan: "PLAN D'ACTION",
      tabListenSecond: "ÉCOUTE APPROFONDIE",
      generating: "Génération…",
      kbActive: "Base de connaissance active",
      clickToDig: "Cliquer sur un élément pour approfondir",
      noContent: "Pas encore de contenu pour cette section.",
      sectionStrengths: "Points forts",
      sectionWeaknesses: "Lacunes",
      sectionRisks: "Risques",
      sectionSuggestions: "Suggestions",
      sectionActions: "Actions prioritaires",
      sectionNextSteps: "Prochaines étapes",
      sectionWhyThis: "Pourquoi ce choix",
      sectionHowToApply: "Comment l'appliquer",
      addVersion: "Ajouter une version",
      compareVersions: "Comparer les versions",
      viewComparison: "Voir la comparaison",
      exportPdf: "Exporter en PDF",
      sharePublic: "Lien public",
      deleteVersion: "Supprimer cette version",
      renameVersion: "Renommer la version",
      scoreOutOf: "/ 100",
      durationLabel: "Durée",
      analysedOn: "Analysé le",
      dawLabel: "DAW",
      versionLabel: "Version",
      projectLabel: "Projet",
      difficulty: "Difficulté",
      impact: "Impact",
      priority: "Priorité",
      priorityHigh: "Haute",
      priorityMedium: "Moyenne",
      priorityLow: "Basse",
      confidenceMeasured: "MESURÉ",
      confidenceIdentified: "IDENTIFIÉ",
      confidenceSuggested: "SUGGÉRÉ",
      retakeAnalysis: "Relancer l'analyse",
      fetchingFiche: "Chargement de la fiche…",
      ficheUnavailable: "Fiche non disponible",
      whatWasAnalysed: "Ce qui a été analysé",
      vocalTypeVocal: "Chanté",
      vocalTypeInstrumental: "Instrumental",
      vocalTypeInstrumentalPending: "Instrumental (voix à venir)",
      vocalTypeInstrumentalFinal: "Instrumental définitif",
    },

    /* ─────────────── COMPARE ─────────────── */
    compare: {
      title: "COMPARAISON DE VERSIONS",
      subtitle: "Ce qui a changé entre tes versions",
      pickA: "Version A",
      pickB: "Version B",
      differences: "Différences",
      improvements: "Progrès",
      regressions: "Régressions",
      suggestions: "Suggestions",
      sameScore: "Score identique",
      scoreDelta: "Écart de score",
      noChange: "Pas de changement notable",
      generating: "Comparaison en cours…",
      empty: "Au moins deux versions analysées sont nécessaires pour comparer.",
      otherTitleDetected: "Attention : ces versions semblent être des titres différents.",
    },

    /* ─────────────── CHAT (contextuel fiche) ─────────────── */
    chat: {
      placeholder: "Pose une question sur cette version…",
      placeholderGeneric: "Ta question…",
      send: "Envoyer",
      loading: "L'IA réfléchit…",
      emptyTitle: "Demande ce que tu veux à l'IA",
      emptySub: "Elle a accès à la fiche, à l'analyse audio et à la base PureMix.",
      suggestionLabel: "Suggestions",
      reset: "Nouvelle conversation",
      errorGeneric: "Une erreur est survenue. Réessaie.",
    },

    /* ─────────────── ASK MODAL ─────────────── */
    ask: {
      title: "POSER UNE QUESTION",
      sub: "Expert production musicale · Tous DAWs",
      placeholder: "Ta question…",
      send: "Envoyer",
      thinking: "Réflexion en cours…",
      exampleLabel: "Exemples",
      examples: [
        "Comment mixer une voix R&B chaude ?",
        "Quel compresseur sur la basse pour du rap ?",
        "Comment éviter le muddy dans un mix ?",
      ],
    },

    /* ─────────────── VERSIONS SCREEN ─────────────── */
    versions: {
      title: "VERSIONS",
      subtitle: "Tes titres et leurs versions",
      empty: "Aucun titre pour l'instant.",
      emptyCta: "Importer mon premier titre",
      searchPlaceholder: "Rechercher un titre, un projet…",
      filterAll: "Tous",
      filterAnalyzed: "Analysés",
      filterPending: "En attente",
      noResults: "Aucun résultat",
      noResultsSub: "Essaie un autre terme ou réinitialise les filtres",
      sortRecent: "Plus récent",
      sortOldest: "Plus ancien",
      sortAlpha: "A → Z",
      sortScore: "Par score",
      versionsCount: "{n} version",
      versionsCountPlural: "{n} versions",
      latestVersion: "Dernière",
      play: "Écouter",
      openFiche: "Voir l'analyse",
      addVersion: "+ Version",
      menuRename: "Renommer",
      menuDelete: "Supprimer",
      menuChangeProject: "Changer de projet",
      menuChangeVocalType: "Type de titre",
      confirmDeleteTrackTitle: "Supprimer ce titre ?",
      confirmDeleteTrackBody: "Toutes les versions et analyses associées seront supprimées. Cette action est irréversible.",
      confirmDeleteVersionTitle: "Supprimer cette version ?",
      confirmDeleteVersionBody: "L'analyse et le fichier audio liés seront effacés. Cette action est irréversible.",
    },

    /* ─────────────── SIDEBAR ─────────────── */
    sidebar: {
      sectionTracks: "Titres",
      sectionProjects: "Projets",
      newTrack: "+ Nouveau titre",
      newProject: "+ Nouveau projet",
      noTracks: "Aucun titre pour le moment",
      menuAddVersion: "Ajouter une version",
      menuRename: "Renommer",
      menuDelete: "Supprimer",
      menuMove: "Déplacer",
      expand: "Déplier",
      collapse: "Replier",
      askAi: "Poser une question",
      homeLink: "Accueil",
      settingsLink: "Réglages",
      signOut: "Se déconnecter",
      premiumBadge: "Premier",
    },

    /* ─────────────── PLAYER ─────────────── */
    player: {
      idle: "Pas de lecture en cours",
      idleHint: "Choisis un titre pour l'écouter",
      prev: "Précédent",
      next: "Suivant",
      toggle: "Lecture / pause",
      loading: "Chargement…",
      noAudio: "Audio indisponible",
      speed: "Vitesse",
    },

    /* ─────────────── RÉGLAGES (propres au composant) ─────── */
    reglages: {
      title: "RÉGLAGES",
      subtitle: "Gérer ton profil et tes préférences",
      sectionAvatar: "PHOTO DE PROFIL",
      sectionProfile: "PROFIL",
      sectionDaw: "DAW PAR DÉFAUT",
      sectionLang: "LANGUE",
      sectionBank: "COORDONNÉES BANCAIRES",
      sectionSecurity: "SÉCURITÉ",
      sectionData: "DONNÉES",
      sectionSubscription: "ABONNEMENT",
      sectionPayment: "PAIEMENT",
      sectionPreferences: "PRÉFÉRENCES",
      avatarHint: "Clique sur l'avatar pour changer ta photo",
      firstName: "PRÉNOM",
      firstNamePlaceholder: "Ton prénom",
      lastName: "NOM",
      lastNamePlaceholder: "Ton nom",
      emailLabel: "EMAIL",
      dawNone: "Aucun (demander à chaque fois)",
      langFrench: "Français",
      langEnglish: "English",
      bankHint: "Ces informations sont chiffrées et utilisées uniquement pour les reversements d'abonnement.",
      bankPremium: "PREMIUM",
      ibanLabel: "IBAN",
      bicLabel: "BIC / SWIFT",
      save: "Enregistrer",
      saving: "Enregistrement...",
      saved: "✓ Enregistré",
      signOut: "Se déconnecter",
      planFree: "5 analyses / mois",
      planCurrent: "PLAN ACTUEL",
      upgrade: "PASSER EN PRO",
      proFeatures: "Analyses illimitées · Export PDF · Assistant enrichi · Historique complet",
      notifNews: "Notifications — Nouveautés",
      dangerZone: "Zone de danger",
      deleteAccount: "Supprimer mon compte",
      exportPdf: "Exporter mes analyses",
      exportPdfDesc: "Télécharger toutes tes fiches en PDF",
      exportData: "Exporter mes données",
      exportDataDesc: "Archive complète au format JSON",
      deleteData: "Supprimer toutes mes données",
      irreversible: "Cette action est irréversible. Toutes tes analyses et préférences seront supprimées.",
      changePhoto: "Changer la photo",
      username: "Nom d'utilisateur",
      noCard: "Aucune carte enregistrée",
      cardRequired: "Requis pour le plan Pro",
      addCard: "Ajouter une carte",
    },

    /* ─────────────── MODALES ─────────────── */
    modals: {
      // Rename
      renameTitle: "Renommer",
      renamePlaceholder: "Nouveau nom",
      renameConfirm: "Renommer",
      // Confirm
      confirmTitle: "Confirmer l'action",
      confirmDeleteDefault: "Cette action est irréversible. Continuer ?",
      // Add version
      addTitle: "Ajouter une version",
      addVersionName: "Nom de la version",
      addVersionPlaceholder: "ex: Mix v3, Master, Radio Edit…",
      addSubmit: "Ajouter",
      // Share link
      shareTitle: "Partager cette fiche",
      shareSub: "Toute personne avec ce lien pourra consulter la fiche.",
      shareCreate: "Créer un lien public",
      shareRevoke: "Désactiver le lien",
      shareCopy: "Copier le lien",
      shareCopied: "Lien copié !",
      // Export PDF
      exportPdfTitle: "Exporter en PDF",
      exportPdfSub: "Choisis le niveau de détail.",
      exportPdfFull: "Fiche complète",
      exportPdfSummary: "Résumé (1 page)",
      exportPdfDownload: "Télécharger",
      exportPdfGenerating: "Génération du PDF…",
      // Onboarding
      onboardingWelcome: "Bienvenue sur VERSIONS",
      onboardingSub: "Analyse, compare et fais évoluer tes productions.",
      onboardingStart: "Commencer",
      onboardingSkip: "Passer",
      onboardingStep1Title: "Upload ton mix",
      onboardingStep1Body: "Envoie ton fichier audio — l'IA fait le reste.",
      onboardingStep2Title: "Lis ta fiche",
      onboardingStep2Body: "Diagnostic détaillé, points forts, lacunes, plan d'action.",
      onboardingStep3Title: "Compare tes versions",
      onboardingStep3Body: "Trace l'évolution de chaque morceau version après version.",
      // Vocal type banner
      vocalBannerTitle: "Ce titre est-il chanté ou instrumental ?",
      vocalBannerBody: "Pour affiner l'analyse et ne pas traiter l'absence de voix comme un défaut à tort.",
      vocalBannerConfirm: "Confirmer",
      vocalBannerLater: "Plus tard",
    },

    /* ─────────────── PUBLIC FICHE (hors app) ───────────── */
    publicFiche: {
      headerShared: "Fiche partagée",
      headerPoweredBy: "Propulsé par",
      cta: "Essaie VERSIONS",
      ctaSub: "Crée ton compte et analyse tes propres titres.",
      expired: "Ce lien n'est plus actif.",
      notFound: "Fiche introuvable.",
    },

    /* ─────────────── ERREURS / MESSAGES ──────────────── */
    errors: {
      generic: "Une erreur est survenue.",
      network: "Connexion interrompue. Vérifie ta connexion internet.",
      uploadFailed: "L'envoi du fichier a échoué.",
      analysisFailed: "L'analyse a échoué. Réessaie dans un instant.",
      fileTooBig: "Fichier trop volumineux (200 MB max).",
      fileType: "Format non supporté. Utilise WAV, AIFF, MP3 ou FLAC.",
      requiredField: "Ce champ est obligatoire.",
      invalidEmail: "Email invalide.",
      weakPassword: "Mot de passe trop court (6 caractères min.).",
      loadProfile: "Impossible de charger ton profil.",
      saveProfile: "Impossible d'enregistrer tes modifications.",
    },

    /* ─────────────── DATE / TIME ─────────────────────── */
    datetime: {
      today: "Aujourd'hui",
      yesterday: "Hier",
      daysAgo: "Il y a {n} jours",
      weeksAgo: "Il y a {n} semaines",
      monthsAgo: "Il y a {n} mois",
      justNow: "À l'instant",
      minutesAgo: "Il y a {n} min",
      hoursAgo: "Il y a {n} h",
      months: [
        "janv", "févr", "mars", "avr", "mai", "juin",
        "juil", "août", "sept", "oct", "nov", "déc",
      ],
      monthsLong: [
        "janvier", "février", "mars", "avril", "mai", "juin",
        "juillet", "août", "septembre", "octobre", "novembre", "décembre",
      ],
    },
  },

  en: {
    /* ─────────────────────────── COMMON ────────────────────── */
    common: {
      loading: "LOADING...",
      save: "Save",
      saving: "Saving...",
      saved: "✓ Saved",
      cancel: "Cancel",
      delete: "Delete",
      rename: "Rename",
      create: "Create",
      close: "Close",
      confirm: "Confirm",
      ok: "OK",
      back: "Back",
      continue: "Continue",
      next: "Next",
      prev: "Previous",
      yes: "Yes",
      no: "No",
      search: "Search",
      reset: "Reset",
      tryAgain: "Try again",
      optional: "(optional)",
      required: "Required",
      copy: "Copy",
      copied: "Copied!",
      share: "Share",
      edit: "Edit",
      add: "Add",
      or: "or",
      of: "of",
      and: "and",
      by: "by",
      to: "to",
      from: "from",
      all: "All",
      none: "None",
      unknown: "Unknown",
      untitled: "Untitled",
      untitledMale: "Untitled",
      pending: "Pending",
      inProgress: "In progress",
      done: "Done",
      more: "More",
      less: "Less",
      showMore: "Show more",
      showLess: "Show less",
      viewDetails: "View details",
      hide: "Hide",
      show: "Show",
      new: "New",
      newFem: "New",
      processing: "Processing…",
      generating: "Generating…",
      analysing: "Analysing…",
      track: "track",
      tracks: "tracks",
      version: "version",
      versions: "versions",
      project: "project",
      projects: "projects",
    },

    /* ─────────────────────────── NAV ───────────────────────── */
    nav: {
      home: "Home",
      versions: "Versions",
      chat: "Chat",
      reglages: "Settings",
      profile: "Profile",
      back: "Back",
      newAnalysis: "New analysis",
    },

    /* ─────────────────────────── BRAND ─────────────────────── */
    brand: {
      tagline: "Audio production versioning",
      taglineAction: "Analyse · Compare · Evolve",
    },

    /* ─────────────────────────── AUTH ──────────────────────── */
    auth: {
      signInTitle: "SIGN IN",
      signUpTitle: "CREATE MY ACCOUNT",
      signInTab: "Sign in",
      signUpTab: "Sign up",
      signIn: "Sign in",
      signUp: "Sign up",
      signOut: "Sign out",
      google: "Continue with Google",
      apple: "Continue with Apple",
      facebook: "Continue with Facebook",
      or: "OR",
      orEmail: "or with email",
      email: "Email",
      password: "Password",
      forgotPassword: "Forgot password?",
      confirmEmail: "Check your email to confirm your account.",
      noAccount: "No account? Sign up",
      alreadyRegistered: "Already registered? Sign in",
      cgu1: "By continuing, you agree to our",
      cgu2: "Terms of Service",
      cgu3: "and",
      cgu4: "Privacy Policy",
    },

    /* ─────────────────────────── HOME / WELCOME ────────────── */
    home: {
      greeting: "HI!",
      greetingWithName: "HI {name}!",
      newTrack: "New track",
      newVersion: "Add a version",
      pickTrack: "Which track?",
      myTracks: "My",
      myTracksAccent: "tracks",
      empty: "Import your first track to start the journey.",
      tipLabel: "Did you know",
      ctaAnalysis: "Analysis",
      playing: "Playing",
      play: "Play",
      pause: "Pause",
      tips: [
        "Taking regular breaks keeps your listening attentive and objective.",
        "Your ears fatigue after 45 min — a 10 min break saves you 2h of work.",
        "Listening to your mix in another context (car, headphones) reveals what the studio hides.",
        "Lowering the monitoring volume helps you spot balance imbalances.",
        "Stepping away from a mix for 24h completely changes your perception.",
        "Regularly comparing against a reference recalibrates your ear and your choices.",
        "Silence between sessions matters as much as the work itself.",
        "Listening at low volume is the best test: if the mix works quiet, it will work loud.",
      ],
    },

    /* ─────────────────────────── INPUT ─────────────────────── */
    input: {
      title: "NEW ANALYSIS",
      tagline: "Analyse · Compare · Evolve",
      sectionMix: "YOUR MIX",
      sectionVocalType: "TRACK TYPE",
      sectionProject: "PROJECT",
      sectionTitle: "TITLE",
      sectionVersion: "VERSION",
      sectionDaw: "YOUR DAW",
      titlePlaceholder: "Track name",
      versionPlaceholder: "e.g. Mix v3, Demo, Master…",
      dawPlaceholder: "Select your DAW…",
      dropText: "Drag the file here or click",
      dropFormats: "WAV · AIFF · MP3 · FLAC — 200 MB max",
      vocalSung: "Vocal",
      vocalInstrumental: "Instrumental",
      vocalVoiceQuestion: "VOCALS ON THIS TRACK?",
      vocalComing: "Coming",
      vocalFinal: "Final instrumental",
      vocalComingTip: "You plan to add vocals on a future version",
      vocalFinalTip: "Purely instrumental piece, no vocals planned",
      vocalHintIdle: "This choice avoids flagging the lack of vocals as a flaw by mistake.",
      vocalHintComing: "The analysis will treat vocals as an upcoming step.",
      vocalHintFinal: "The vocal section will be ignored in the analysis and score.",
      projectPickerFirst: "+ Create your first project",
      projectPickerNew: "+ New project",
      projectLocked: "Project locked — this track is already attached to a project",
      projectLockedHint: "Project locked — this track already belongs to this project.",
      analyze: "Analyse",
      fieldsRemaining: "{filled}/{total} fields filled",
      newProjectTitle: "New project",
      newProjectPlaceholder: "Project name",
    },

    /* ─────────────────────────── LOADING ───────────────────── */
    loading: {
      title: "ANALYSIS IN PROGRESS",
      sub: "Your mix is being dissected.",
      cancel: "Cancel analysis",
      stepUpload: "Uploading file",
      stepListen: "Qualitative listening",
      stepExtract: "Extracting elements",
      stepDetectVocal: "Vocal detection",
      stepBuildFiche: "Building the report",
      stepSynthesis: "Final synthesis",
      stageListening: "Gemini is listening to your track…",
      stageAnalyzing: "Claude is writing the diagnostic…",
      stageRag: "Cross-checking with the PureMix knowledge base…",
      stageFinal: "Final review…",
      errorTitle: "Analysis failed",
      errorRetry: "Try again",
      errorBack: "Go back",
    },

    /* ─────────────────────────── FICHE ─────────────────────── */
    fiche: {
      headerBadgeRef: "REFERENCE MODE",
      headerBadgePerso: "PERSONAL MODE",
      headerVerdict: "VERDICT",
      headerScore: "SCORE",
      tabAnalysis: "ANALYSIS",
      tabAnalysisPerso: "DIAGNOSTIC",
      tabListen: "LISTENING",
      tabListenPerso: "FEELING",
      tabChain: "PROBABLE CHAIN",
      tabChainPerso: "ISSUES FOUND",
      tabPlugins: "PLUGINS IDENTIFIED",
      tabPluginsPerso: "RECOMMENDED TOOLS",
      tabReproduce: "REPRODUCE",
      tabActionPlan: "ACTION PLAN",
      tabListenSecond: "DEEP LISTENING",
      generating: "Generating…",
      kbActive: "Knowledge base active",
      clickToDig: "Click an element to dig deeper",
      noContent: "No content yet for this section.",
      sectionStrengths: "Strengths",
      sectionWeaknesses: "Weaknesses",
      sectionRisks: "Risks",
      sectionSuggestions: "Suggestions",
      sectionActions: "Priority actions",
      sectionNextSteps: "Next steps",
      sectionWhyThis: "Why this choice",
      sectionHowToApply: "How to apply it",
      addVersion: "Add a version",
      compareVersions: "Compare versions",
      viewComparison: "View comparison",
      exportPdf: "Export as PDF",
      sharePublic: "Public link",
      deleteVersion: "Delete this version",
      renameVersion: "Rename version",
      scoreOutOf: "/ 100",
      durationLabel: "Duration",
      analysedOn: "Analysed on",
      dawLabel: "DAW",
      versionLabel: "Version",
      projectLabel: "Project",
      difficulty: "Difficulty",
      impact: "Impact",
      priority: "Priority",
      priorityHigh: "High",
      priorityMedium: "Medium",
      priorityLow: "Low",
      confidenceMeasured: "MEASURED",
      confidenceIdentified: "IDENTIFIED",
      confidenceSuggested: "SUGGESTED",
      retakeAnalysis: "Re-run analysis",
      fetchingFiche: "Loading report…",
      ficheUnavailable: "Report unavailable",
      whatWasAnalysed: "What was analysed",
      vocalTypeVocal: "Vocal",
      vocalTypeInstrumental: "Instrumental",
      vocalTypeInstrumentalPending: "Instrumental (vocals coming)",
      vocalTypeInstrumentalFinal: "Final instrumental",
    },

    /* ─────────────── COMPARE ─────────────── */
    compare: {
      title: "VERSION COMPARISON",
      subtitle: "What changed between your versions",
      pickA: "Version A",
      pickB: "Version B",
      differences: "Differences",
      improvements: "Improvements",
      regressions: "Regressions",
      suggestions: "Suggestions",
      sameScore: "Identical score",
      scoreDelta: "Score delta",
      noChange: "No notable change",
      generating: "Comparing…",
      empty: "At least two analysed versions are needed to compare.",
      otherTitleDetected: "Warning: these versions appear to be different tracks.",
    },

    /* ─────────────── CHAT (fiche-contextual) ─────────────── */
    chat: {
      placeholder: "Ask a question about this version…",
      placeholderGeneric: "Your question…",
      send: "Send",
      loading: "The AI is thinking…",
      emptyTitle: "Ask the AI anything",
      emptySub: "It has access to the report, the audio analysis and the PureMix library.",
      suggestionLabel: "Suggestions",
      reset: "New conversation",
      errorGeneric: "Something went wrong. Try again.",
    },

    /* ─────────────── ASK MODAL ─────────────── */
    ask: {
      title: "ASK A QUESTION",
      sub: "Music production expert · All DAWs",
      placeholder: "Your question…",
      send: "Send",
      thinking: "Thinking…",
      exampleLabel: "Examples",
      examples: [
        "How do I mix a warm R&B vocal?",
        "Which compressor on bass for rap?",
        "How do I avoid muddy mixes?",
      ],
    },

    /* ─────────────── VERSIONS SCREEN ─────────────── */
    versions: {
      title: "VERSIONS",
      subtitle: "Your tracks and their versions",
      empty: "No tracks yet.",
      emptyCta: "Import my first track",
      searchPlaceholder: "Search by title, project…",
      filterAll: "All",
      filterAnalyzed: "Analysed",
      filterPending: "Pending",
      noResults: "No results",
      noResultsSub: "Try different terms or reset filters",
      sortRecent: "Most recent",
      sortOldest: "Oldest",
      sortAlpha: "A → Z",
      sortScore: "By score",
      versionsCount: "{n} version",
      versionsCountPlural: "{n} versions",
      latestVersion: "Latest",
      play: "Play",
      openFiche: "View analysis",
      addVersion: "+ Version",
      menuRename: "Rename",
      menuDelete: "Delete",
      menuChangeProject: "Change project",
      menuChangeVocalType: "Track type",
      confirmDeleteTrackTitle: "Delete this track?",
      confirmDeleteTrackBody: "All versions and analyses will be removed. This action is irreversible.",
      confirmDeleteVersionTitle: "Delete this version?",
      confirmDeleteVersionBody: "The analysis and the linked audio file will be deleted. This action is irreversible.",
    },

    /* ─────────────── SIDEBAR ─────────────── */
    sidebar: {
      sectionTracks: "Tracks",
      sectionProjects: "Projects",
      newTrack: "+ New track",
      newProject: "+ New project",
      noTracks: "No tracks yet",
      menuAddVersion: "Add a version",
      menuRename: "Rename",
      menuDelete: "Delete",
      menuMove: "Move",
      expand: "Expand",
      collapse: "Collapse",
      askAi: "Ask a question",
      homeLink: "Home",
      settingsLink: "Settings",
      signOut: "Sign out",
      premiumBadge: "Premier",
    },

    /* ─────────────── PLAYER ─────────────── */
    player: {
      idle: "Nothing playing",
      idleHint: "Pick a track to listen",
      prev: "Previous",
      next: "Next",
      toggle: "Play / pause",
      loading: "Loading…",
      noAudio: "Audio unavailable",
      speed: "Speed",
    },

    /* ─────────────── SETTINGS ─────────────── */
    reglages: {
      title: "SETTINGS",
      subtitle: "Manage your profile and preferences",
      sectionAvatar: "PROFILE PICTURE",
      sectionProfile: "PROFILE",
      sectionDaw: "DEFAULT DAW",
      sectionLang: "LANGUAGE",
      sectionBank: "BANK DETAILS",
      sectionSecurity: "SECURITY",
      sectionData: "DATA",
      sectionSubscription: "SUBSCRIPTION",
      sectionPayment: "PAYMENT",
      sectionPreferences: "PREFERENCES",
      avatarHint: "Click the avatar to change your picture",
      firstName: "FIRST NAME",
      firstNamePlaceholder: "Your first name",
      lastName: "LAST NAME",
      lastNamePlaceholder: "Your last name",
      emailLabel: "EMAIL",
      dawNone: "None (ask every time)",
      langFrench: "Français",
      langEnglish: "English",
      bankHint: "These details are encrypted and only used for subscription payouts.",
      bankPremium: "PREMIUM",
      ibanLabel: "IBAN",
      bicLabel: "BIC / SWIFT",
      save: "Save",
      saving: "Saving...",
      saved: "✓ Saved",
      signOut: "Sign out",
      planFree: "5 analyses / month",
      planCurrent: "CURRENT PLAN",
      upgrade: "GO PRO",
      proFeatures: "Unlimited analyses · PDF export · Enhanced assistant · Full history",
      notifNews: "Notifications — News & updates",
      dangerZone: "Danger zone",
      deleteAccount: "Delete my account",
      exportPdf: "Export my analyses",
      exportPdfDesc: "Download all your reports as PDF",
      exportData: "Export my data",
      exportDataDesc: "Full archive in JSON format",
      deleteData: "Delete all my data",
      irreversible: "This action is irreversible. All your analyses and preferences will be deleted.",
      changePhoto: "Change photo",
      username: "Username",
      noCard: "No card on file",
      cardRequired: "Required for Pro plan",
      addCard: "Add a card",
    },

    /* ─────────────── MODALS ─────────────── */
    modals: {
      renameTitle: "Rename",
      renamePlaceholder: "New name",
      renameConfirm: "Rename",
      confirmTitle: "Confirm action",
      confirmDeleteDefault: "This action is irreversible. Continue?",
      addTitle: "Add a version",
      addVersionName: "Version name",
      addVersionPlaceholder: "e.g. Mix v3, Master, Radio Edit…",
      addSubmit: "Add",
      shareTitle: "Share this report",
      shareSub: "Anyone with this link can view the report.",
      shareCreate: "Create a public link",
      shareRevoke: "Disable the link",
      shareCopy: "Copy link",
      shareCopied: "Link copied!",
      exportPdfTitle: "Export as PDF",
      exportPdfSub: "Choose the level of detail.",
      exportPdfFull: "Full report",
      exportPdfSummary: "Summary (1 page)",
      exportPdfDownload: "Download",
      exportPdfGenerating: "Generating PDF…",
      onboardingWelcome: "Welcome to VERSIONS",
      onboardingSub: "Analyse, compare and evolve your productions.",
      onboardingStart: "Get started",
      onboardingSkip: "Skip",
      onboardingStep1Title: "Upload your mix",
      onboardingStep1Body: "Send your audio file — the AI does the rest.",
      onboardingStep2Title: "Read your report",
      onboardingStep2Body: "Detailed diagnostic, strengths, weaknesses, action plan.",
      onboardingStep3Title: "Compare your versions",
      onboardingStep3Body: "Track the evolution of each song version after version.",
      vocalBannerTitle: "Is this track vocal or instrumental?",
      vocalBannerBody: "To refine the analysis and avoid flagging missing vocals as a flaw by mistake.",
      vocalBannerConfirm: "Confirm",
      vocalBannerLater: "Later",
    },

    /* ─────────────── PUBLIC FICHE ───────────── */
    publicFiche: {
      headerShared: "Shared report",
      headerPoweredBy: "Powered by",
      cta: "Try VERSIONS",
      ctaSub: "Create your account and analyse your own tracks.",
      expired: "This link is no longer active.",
      notFound: "Report not found.",
    },

    /* ─────────────── ERRORS ─────────────── */
    errors: {
      generic: "Something went wrong.",
      network: "Connection interrupted. Check your internet.",
      uploadFailed: "File upload failed.",
      analysisFailed: "Analysis failed. Try again in a moment.",
      fileTooBig: "File too large (200 MB max).",
      fileType: "Unsupported format. Use WAV, AIFF, MP3 or FLAC.",
      requiredField: "This field is required.",
      invalidEmail: "Invalid email.",
      weakPassword: "Password too short (6 characters min.).",
      loadProfile: "Unable to load your profile.",
      saveProfile: "Unable to save your changes.",
    },

    /* ─────────────── DATE / TIME ───────────── */
    datetime: {
      today: "Today",
      yesterday: "Yesterday",
      daysAgo: "{n} days ago",
      weeksAgo: "{n} weeks ago",
      monthsAgo: "{n} months ago",
      justNow: "Just now",
      minutesAgo: "{n} min ago",
      hoursAgo: "{n} h ago",
      months: [
        "Jan", "Feb", "Mar", "Apr", "May", "Jun",
        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
      ],
      monthsLong: [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
      ],
    },
  },
};

/* ────────────────────────────────────────────────────────────
 * Helper `pick(lang, 'fiche.tabAnalysis')` — accès pointé pratique
 * avec fallback FR si clé manquante en EN (et vice-versa).
 * ──────────────────────────────────────────────────────────── */
export function pick(lang, path, vars) {
  const walk = (obj) => {
    try {
      return path.split(".").reduce((acc, k) => (acc == null ? undefined : acc[k]), obj);
    } catch { return undefined; }
  };
  let v = walk(STRINGS[lang]);
  if (v == null) v = walk(STRINGS.fr); // fallback FR
  if (typeof v === "string" && vars) {
    Object.keys(vars).forEach((k) => {
      v = v.replace(new RegExp(`\\{${k}\\}`, "g"), vars[k]);
    });
  }
  return v == null ? path : v;
}

export default STRINGS;
