const INSTRUMENTS_DB = {
  synth_subtractive: {
    label: "Synthèse soustractive",
    paid: [
      { name:"Serum",                  brand:"Xfer Records",    desc:"Standard wavetable moderne — son de référence EDM/pop.", price:"~200€" },
      { name:"Vital",                  brand:"Matt Tytel",      desc:"Alternative Serum — wavetable de haute qualité, version gratuite disponible.", price:"Freemium" },
      { name:"Sylenth1",               brand:"LennarDigital",   desc:"Soustractif analogique virtuel — chaleur et punch légendaires.", price:"~170€" },
      { name:"Massive X",              brand:"Native Instruments", desc:"Wavetable moderne NI — sons complexes et évolutifs.", price:"inclus Komplete" },
      { name:"Massive",                brand:"Native Instruments", desc:"Le wavetable qui a défini le son dubstep/EDM 2010s.", price:"inclus Komplete" },
      { name:"Moog Subsequent 37 (plugin)", brand:"Moog",       desc:"Émulation Moog — basses et leads analogiques authentiques.", price:"~300€" },
      { name:"Arturia MiniMoog V",     brand:"Arturia",         desc:"Émulation Minimoog — basses et leads vintage de référence.", price:"inclus V Collection" },
      { name:"Arturia Prophet-5 V",    brand:"Arturia",         desc:"Émulation Sequential Prophet-5 — polysynth vintage riche.", price:"inclus V Collection" },
      { name:"Arturia Juno-106 V",     brand:"Arturia",         desc:"Émulation Roland Juno-106 — chorus signature, pads chauds.", price:"inclus V Collection" },
      { name:"Arturia Jupiter-8 V",    brand:"Arturia",         desc:"Émulation Roland Jupiter-8 — le polysynth analogique ultime.", price:"inclus V Collection" },
      { name:"u-he Diva",              brand:"u-he",            desc:"Émulation analogique ultra-réaliste — le plus précis du marché.", price:"~179€" },
      { name:"u-he Repro-1 / Repro-5", brand:"u-he",           desc:"Émulation Pro-One et Prophet-5 — fidélité analogique maximale.", price:"~99€" },
      { name:"u-he Hive 2",            brand:"u-he",            desc:"Soustractif moderne rapide — son immédiat et polyvalent.", price:"~149€" },
      { name:"Omnisphere 2",           brand:"Spectrasonics",   desc:"Bibliothèque de sons massive — synthèse hybride unique.", price:"~500€" },
    ],
    free: [
      { name:"Vital",                  brand:"Matt Tytel",      desc:"Wavetable synth professionnel — version gratuite très complète." },
      { name:"Surge XT",               brand:"Surge Synth Team", desc:"Open-source wavetable — énorme preset bank, qualité pro." },
      { name:"OB-Xd",                  brand:"discoDSP",        desc:"Émulation Oberheim OB-X gratuite — son analogique vintage." },
      { name:"Helm",                   brand:"Matt Tytel",      desc:"Précurseur de Vital — soustractif gratuit solide." },
    ],
    daw_native: {
      "Logic Pro":    ["ES2 (soustractif polyvalent)", "Retro Synth (vintage analogique/FM/wavetable)", "ES1 (basses analogiques)", "ES E (polysynth simple)"],
      "Ableton Live": ["Wavetable (wavetable moderne)", "Analog (émulation analogique)", "Operator (FM synthesis)", "Drift (monosynth analogique)"],
      "FL Studio":    ["Harmor (additive/resynthèse)", "Sytrus (FM avancé)", "3x OSC (soustractif simple)", "GMS (Groove Machine Synth)"],
      "Pro Tools":    ["Vacuum (triode vintage)", "DB-33 (orgue tonewheel)"],
      "Cubase":       ["HALion Sonic SE (multi)", "Retrologue 2 (analogique virtuel)", "Padshop 2 (granulaire)"],
      "Studio One":   ["Mai Tai (polysynth analogique)", "Mojito (monosynth simple)"],
      "Reaper":       ["Aucun natif — bibliothèque VST tierce recommandée"],
    },
  },
  synth_fm: {
    label: "Synthèse FM",
    paid: [
      { name:"FM8",                    brand:"Native Instruments", desc:"FM 6 opérateurs — standard de la synthèse FM logicielle.", price:"inclus Komplete" },
      { name:"Arturia DX7 V",          brand:"Arturia",         desc:"Émulation Yamaha DX7 — le son FM emblématique des années 80.", price:"inclus V Collection" },
      { name:"Native Instruments Operator (Ableton)", brand:"Ableton", desc:"FM 4 opérateurs intégré Live — polyvalent et musical.", price:"inclus Live Suite" },
      { name:"Plogue Chipsynth",       brand:"Plogue",          desc:"Émulation chips FM vintage (OPL, OPM) — lo-fi expressif.", price:"~95€" },
    ],
    free: [
      { name:"Dexed",                  brand:"Digital Suburban", desc:"Émulation DX7 gratuite et fidèle — patches DX7 compatibles." },
      { name:"OPL3 emulator",          brand:"divers",          desc:"Émulation chip FM Yamaha OPL3 — son jeux vidéo vintage." },
    ],
    daw_native: {
      "Ableton Live": ["Operator — FM 4 opérateurs complet"],
      "FL Studio":    ["Sytrus — FM 6 opérateurs + soustractif"],
      "Logic Pro":    ["Alchemy (FM partiel)", "ES2 (FM mode disponible)"],
      "Cubase":       ["Retrologue 2 (FM partiel)"],
    },
  },
  synth_wavetable: {
    label: "Wavetable & Spectral",
    paid: [
      { name:"Serum",                  brand:"Xfer Records",    desc:"Standard wavetable — wavetable custom, modulation visuelle.", price:"~200€" },
      { name:"Phase Plant",            brand:"Kilohearts",      desc:"Synthèse modulaire wavetable — architecture flexible unique.", price:"~200€" },
      { name:"Pigments 4",             brand:"Arturia",         desc:"Synth hybride wavetable/granulaire/additif/FM — très créatif.", price:"~99€" },
      { name:"Falcon 2",               brand:"UVI",             desc:"Plate-forme synthesis hybride — scripting avancé.", price:"~350€" },
      { name:"Nave",                   brand:"Waldorf",         desc:"Wavetable basé sur le Waldorf Wave — sons spectraux uniques.", price:"~50€" },
    ],
    free: [
      { name:"Vital",                  brand:"Matt Tytel",      desc:"Wavetable pro gratuit — qualité Serum, 100% libre." },
      { name:"Surge XT",               brand:"Surge Synth Team", desc:"Wavetable open source — aliasing minimal, très expressif." },
    ],
    daw_native: {
      "Ableton Live": ["Wavetable — wavetable natif avec filtres vintage"],
      "Logic Pro":    ["Alchemy — wavetable + granulaire + additif"],
      "FL Studio":    ["Harmor — additive/resynthèse de spectres"],
      "Cubase":       ["Padshop 2 — granulaire/wavetable"],
    },
  },
  synth_granular: {
    label: "Granulaire & Textural",
    paid: [
      { name:"Granulator III (Ableton)", brand:"Ableton/Robert Henke", desc:"Granulaire temps réel — textural, expérimental, unique.", price:"gratuit avec Live" },
      { name:"Output Portal",          brand:"Output",          desc:"Granulaire temps réel sur n'importe quelle source.", price:"~99€" },
      { name:"Emergence",              brand:"Zynaptiq",        desc:"Granulaire AI — génère des sons à partir d'audio existant.", price:"~149€" },
      { name:"Iris 2",                 brand:"iZotope",         desc:"Synthèse par spectrogramme — manipulation visuelle du son.", price:"~99€" },
    ],
    free: [
      { name:"Padawan",                brand:"Various",         desc:"Granulaire simple gratuit — bon pour l'apprentissage." },
      { name:"Alchemy (Logic)",        brand:"Apple",           desc:"Granulaire natif Logic — inclus dans Logic Pro." },
    ],
    daw_native: {
      "Logic Pro":    ["Alchemy — granulaire avancé intégré"],
      "Ableton Live": ["Granulator III (Max for Live gratuit)", "Meld — granulaire basique"],
      "Cubase":       ["Padshop 2 — granulaire natif"],
    },
  },
  sampler: {
    label: "Samplers & ROMplers",
    paid: [
      { name:"Kontakt 7",              brand:"Native Instruments", desc:"Standard de l'industrie — bibliothèque massive, scripting avancé.", price:"inclus Komplete / ~400€" },
      { name:"PLAY (EastWest)",        brand:"EastWest",        desc:"Moteur EastWest — orchestral, cinéma, productions premium.", price:"abonnement ~30€/mois" },
      { name:"UVI Workstation",        brand:"UVI",             desc:"Lecteur de bibliothèques UVI — sons vintage et modernes.", price:"gratuit (bibliothèques payantes)" },
      { name:"HALion 7",               brand:"Steinberg",       desc:"Sampler/synthèse intégré — natif Cubase, très polyvalent.", price:"~350€" },
      { name:"SampleTank 4",           brand:"IK Multimedia",   desc:"ROMpler et sampler — grande bibliothèque intégrée.", price:"~200€" },
      { name:"Keyscape",               brand:"Spectrasonics",   desc:"Pianos et claviers samplés premium — son exceptionnel.", price:"~400€" },
      { name:"Ravenscroft 275",        brand:"Vienna Symphonic Library", desc:"Piano de concert samplé — référence absolue.", price:"~350€" },
    ],
    free: [
      { name:"LABS",                   brand:"Spitfire Audio",  desc:"Instruments samplés gratuits de haute qualité — mis à jour régulièrement." },
      { name:"BBC Symphony Discover",  brand:"Spitfire Audio",  desc:"Orchestre symphonique BBC gratuit — qualité broadcast." },
      { name:"MT Power Drum Kit 2",    brand:"Prominy",         desc:"Batterie acoustique samplée gratuite — son naturel." },
      { name:"Vital (presets)",        brand:"communauté",      desc:"Bibliothèques de presets Vital — vastes ressources gratuites." },
    ],
    daw_native: {
      "Logic Pro":    ["EXS24/Sampler (sampler natif)", "Quick Sampler (slicing)"],
      "Ableton Live": ["Sampler (full)", "Simpler (basique)", "Drum Rack"],
      "FL Studio":    ["DirectWave (sampler complet)", "FPC (drum pads)"],
      "Pro Tools":    ["Structure Free (sampler Avid)"],
      "Cubase":       ["HALion Sonic SE (inclus)"],
      "Studio One":   ["Impact XT (drums)", "Sample One XT (sampler)"],
      "Reaper":       ["ReaSamplOmatic5000 (natif)"],
    },
  },
  drums: {
    label: "Batteries & Percussions",
    paid: [
      { name:"Superior Drummer 3",     brand:"Toontrack",       desc:"Référence batterie acoustique — samples multi-microphones.", price:"~350€" },
      { name:"EZdrummer 3",            brand:"Toontrack",       desc:"Batterie acoustique accessible — songwriting assisté.", price:"~200€" },
      { name:"BFD3",                   brand:"FXpansion/inMusic", desc:"Batterie acoustique ultra-réaliste — mixage avancé.", price:"~200€" },
      { name:"Addictive Drums 2",      brand:"XLN Audio",       desc:"Batterie acoustique — sons prêts à l'emploi, très musical.", price:"~160€" },
      { name:"Steven Slate Drums 5",   brand:"Slate Digital",   desc:"Batterie acoustique + trigger — sons modernes de prod.", price:"abonnement ~15€/mois" },
      { name:"Battery 4",              brand:"Native Instruments", desc:"Drum machine — samples électroniques et acoustiques.", price:"inclus Komplete" },
      { name:"Drum Synth (Live)",      brand:"Ableton",         desc:"Synthèse de percussions — chaque élément est synthétisé.", price:"inclus Live Suite" },
    ],
    free: [
      { name:"MT Power Drum Kit 2",    brand:"Prominy",         desc:"Batterie acoustique samplée gratuite et convaincante." },
      { name:"DrumMic'a",              brand:"Sennheiser",      desc:"Batterie acoustique multi-micro gratuite — très détaillée." },
      { name:"LABS Drumming",          brand:"Spitfire Audio",  desc:"Batteries acoustiques gratuites Spitfire." },
    ],
    daw_native: {
      "Logic Pro":    ["Drum Machine Designer", "Ultrabeat (drum synth)"],
      "Ableton Live": ["Drum Rack", "Drum Synth (Suite)", "Beat Tools"],
      "FL Studio":    ["FPC (pads)", "Drumpad"],
      "Pro Tools":    ["Boom (drum machine basique)"],
      "Cubase":       ["Beat Designer", "HALion Sonic SE drums"],
      "Studio One":   ["Impact XT"],
      "Reaper":       ["Aucun natif spécifique — VST tiers"],
    },
  },
  piano_keys: {
    label: "Pianos & Claviers",
    paid: [
      { name:"Keyscape",               brand:"Spectrasonics",   desc:"Pianos et claviers vintage samplés — qualité inégalée.", price:"~400€" },
      { name:"Ravenscroft 275",        brand:"Vienna Symphonic Library", desc:"Piano de concert — référence mastering et prod.", price:"~350€" },
      { name:"Pianoteq 8",             brand:"Modartt",         desc:"Modélisation physique — piano sans samples, très léger.", price:"~300€" },
      { name:"Alicia's Keys",          brand:"Native Instruments", desc:"Yamaha C3 samplé par Alicia Keys — son doux et intime.", price:"inclus Komplete" },
      { name:"Scarbee Vintage Keys",   brand:"Native Instruments", desc:"Claviers vintage (Rhodes, Wurli, Clavinet) — référence.", price:"inclus Komplete" },
      { name:"Mark Studio 2",          brand:"IK Multimedia",   desc:"Rhodes électrique — émulation ultra-réaliste.", price:"~150€" },
      { name:"B-3X",                   brand:"IK Multimedia",   desc:"Hammond B-3 avec Leslie — le meilleur émulateur orgue.", price:"~150€" },
    ],
    free: [
      { name:"LABS Soft Piano",        brand:"Spitfire Audio",  desc:"Piano préparé doux — textures intimistes gratuites." },
      { name:"Decent Sampler (presets)",brand:"Plugin Boutique", desc:"Moteur gratuit + banques piano gratuites de la communauté." },
      { name:"FreePiano",              brand:"divers",          desc:"Piano simple gratuit — apport basique mais fonctionnel." },
    ],
    daw_native: {
      "Logic Pro":    ["Steinway Grand Piano (EXS24)", "Vintage Electric Piano (Rhodes/Wurli)", "Vintage Clav", "Vintage Organ"],
      "Ableton Live": ["Piano & Keys (inclus avec Live)", "Electric (Rhodes/Wurli modélisé)"],
      "FL Studio":    ["FL Keys", "FLEX presets piano"],
      "Cubase":       ["HALion Sonic SE — grands pianos et électriques"],
      "Studio One":   ["Presence XT — presets piano"],
      "Reaper":       ["Aucun natif — ReaSamplOmatic + soundfonts"],
    },
  },
  orchestral: {
    label: "Orchestral & Cinématique",
    paid: [
      { name:"Spitfire BBCSO Professional", brand:"Spitfire Audio", desc:"BBC Symphony Orchestra — référence orchestrale broadcast.", price:"~600€" },
      { name:"Vienna Symphonic Library", brand:"VSL",            desc:"Standard industrie musique de film — réalisme exceptionnel.", price:"~500€+" },
      { name:"EastWest Hollywood Orchestra", brand:"EastWest",  desc:"Hollywood strings/brass/woodwinds — son de blockbuster.", price:"abonnement ~30€/mois" },
      { name:"Cinematic Studio Series", brand:"Cinematic Studio", desc:"Cordes, cuivres, bois cinématiques — légato naturel.", price:"~400€ la série" },
      { name:"LASS (LA Scoring Strings)", brand:"Audiobro",     desc:"Cordes de session LA — articulations naturelles.", price:"~300€" },
    ],
    free: [
      { name:"BBC Symphony Discover",  brand:"Spitfire Audio",  desc:"Version gratuite BBC Symphony — qualité broadcast réelle." },
      { name:"LABS Strings / Brass",   brand:"Spitfire Audio",  desc:"Instruments orchestraux LABS gratuits." },
      { name:"Virtual Playing Orchestra", brand:"Paul Battersby", desc:"Orchestre complet gratuit — bon point de départ." },
    ],
    daw_native: {
      "Logic Pro":    ["Studio Strings", "Studio Horns", "Studio Brass — orchestral natif haute qualité"],
      "Cubase":       ["HALion Sonic SE orchestral presets"],
      "GarageBand":   ["Sections orchestrales intégrées"],
    },
  },
  bass: {
    label: "Basses",
    paid: [
      { name:"Scarbee Bass Series",    brand:"Native Instruments", desc:"Précision, Jay Bass, MM-Bass — basses samplées référence.", price:"inclus Komplete" },
      { name:"Trilian",                brand:"Spectrasonics",   desc:"Basse acoustique, électrique, synth — bibliothèque complète.", price:"~300€" },
      { name:"Modo Bass 2",            brand:"IK Multimedia",   desc:"Modélisation physique basse — jeu de cordes réaliste.", price:"~150€" },
      { name:"Session Bassist (series)",brand:"Native Instruments", desc:"Basses samplées avec patterns — Ultra Bass, Prime Bass.", price:"inclus Komplete" },
    ],
    free: [
      { name:"LABS Bass Guitar",       brand:"Spitfire Audio",  desc:"Basse électrique samplée LABS gratuite." },
      { name:"4Front Bass",            brand:"4Front Technologies", desc:"Basse électrique simple et légère." },
    ],
    daw_native: {
      "Logic Pro":    ["Studio Bass (samplé réaliste)", "Bass Amp Designer"],
      "Ableton Live": ["Bass presets dans Sampler/Wavetable"],
      "GarageBand":   ["Smart Bass", "basses électriques et acoustiques intégrées"],
    },
  },
};

export default INSTRUMENTS_DB;
