const PLUGINS_DB = {
  eq: {
    label: "EQ",
    paid: [
      { name:"FabFilter Pro-Q 4",      brand:"FabFilter",  desc:"EQ de référence — dynamic EQ, linear phase, zero latency. Standard de l'industrie.", price:"~179€" },
      { name:"Waves Q10",              brand:"Waves",       desc:"EQ paramétrique classique, large adoption en studio.", price:"~30€" },
      { name:"Waves SSL E-Channel",    brand:"Waves",       desc:"Émulation console SSL 4000E — chaleur analogique, coloration.", price:"~30€" },
      { name:"Waves API 550A/550B",    brand:"Waves",       desc:"Émulation console API — punch et caractère sur les bus.", price:"~30€" },
      { name:"UAD Neve 1073",          brand:"Universal Audio", desc:"Émulation préamp/EQ Neve légendaire. Coloration vintage.", price:"~150€" },
      { name:"UAD API 560",            brand:"Universal Audio", desc:"EQ graphique 10 bandes API, couleur musicale.", price:"~150€" },
      { name:"iZotope Ozone EQ",       brand:"iZotope",    desc:"EQ avec matching spectral IA et analyse comparative.", price:"inclus Ozone" },
      { name:"Kirchhoff EQ",           brand:"Three-Body Technology", desc:"EQ moderne ultra-précis avec émulations analogiques.", price:"~129€" },
      { name:"Pultec EQP-1A",          brand:"Universal Audio", desc:"EQ à tubes vintage — boost/cut simultané pour la magie Pultec.", price:"~150€" },
      { name:"Sonnox Oxford EQ",       brand:"Sonnox",     desc:"EQ haute précision, favoris broadcast et mastering.", price:"~250€" },
    ],
    free: [
      { name:"TDR Nova",               brand:"Tokyo Dawn",  desc:"EQ dynamique professionnel gratuit — qualité studio." },
      { name:"ReaEQ",                  brand:"Cockos (Reaper)", desc:"EQ paramétrique solide, inclus dans Reaper, utilisable partout." },
      { name:"Voxengo Marvel GEQ",     brand:"Voxengo",    desc:"EQ graphique 16 bandes de qualité professionnelle." },
      { name:"MEqualizer",             brand:"MeldaProduction", desc:"EQ paramétrique 6 bandes clean et précis." },
      { name:"Blue Cat's Triple EQ",   brand:"Blue Cat Audio", desc:"EQ 3 bandes simple et efficace, zéro latence." },
    ],
  },
  compression: {
    label: "Compression",
    paid: [
      { name:"FabFilter Pro-C 2",      brand:"FabFilter",  desc:"Compresseur de référence — 8 modes (Clean, Classic, Opto, Vocal…), sidechain EQ intégré.", price:"~179€" },
      { name:"Waves CLA-76",           brand:"Waves",       desc:"Émulation 1176 FET — attaque ultrarapide, punch sur drums/basse.", price:"~30€" },
      { name:"Waves CLA-2A",           brand:"Waves",       desc:"Émulation LA-2A opto — douceur sur voix et basse.", price:"~30€" },
      { name:"Waves SSL G-Master Buss",brand:"Waves",       desc:"Compresseur de bus SSL G — glue légendaire sur le mix bus.", price:"~30€" },
      { name:"Waves API 2500",         brand:"Waves",       desc:"Compresseur API — ton agressif et punchy, drums/bus.", price:"~30€" },
      { name:"UAD 1176 Classic",       brand:"Universal Audio", desc:"Émulation 1176 Rev A — le compresseur FET de référence.", price:"~150€" },
      { name:"UAD LA-2A",              brand:"Universal Audio", desc:"Compresseur opto vintage, transparent et musical sur voix.", price:"~150€" },
      { name:"UAD Neve 33609",         brand:"Universal Audio", desc:"Compresseur/limiteur Neve broadcast — glue analogique.", price:"~150€" },
      { name:"UAD SSL G-Bus",          brand:"Universal Audio", desc:"Bus compressor SSL en émulation UAD — référence absolue.", price:"~150€" },
      { name:"iZotope Neutron Compressor", brand:"iZotope", desc:"Compresseur avec assistant IA — analyse spectrale et suggestions.", price:"inclus Neutron" },
      { name:"Klanghelm MJUC",         brand:"Klanghelm",  desc:"Compresseur à tubes vintage — chaleur exceptionnelle.", price:"~40€" },
      { name:"Softube Tube-Tech CL 1B",brand:"Softube",    desc:"Émulation compresseur opto Tube-Tech — voix et instruments.", price:"~199€" },
      { name:"Eventide Omnipressor",   brand:"Eventide",   desc:"Compresseur/gate/expander créatif — expansion dynamique unique.", price:"~99€" },
    ],
    free: [
      { name:"TDR Kotelnikov",         brand:"Tokyo Dawn",  desc:"Compresseur de mastering transparent — qualité commerciale gratuite." },
      { name:"Variety of Sound BootEQ/Density",brand:"VoS", desc:"Suite vintage analogique gratuite — compresseurs colorés." },
      { name:"DC1A",                   brand:"Klanghelm",  desc:"Compresseur 2 boutons, son musical immédiat." },
      { name:"MCompressor",            brand:"MeldaProduction", desc:"Compresseur transparent et précis avec visualisation." },
      { name:"OldSkoolVerb/MJUC Jr",   brand:"Klanghelm",  desc:"Version lite de MJUC — chaleur analogique gratuite." },
    ],
  },
  reverb: {
    label: "Réverbe & Delay",
    paid: [
      { name:"Valhalla Room",          brand:"Valhalla DSP", desc:"Réverbe room algorithmique de référence — dense, musicale, pas chère.", price:"~50€" },
      { name:"Valhalla Vintage Verb",  brand:"Valhalla DSP", desc:"Émulation réverbes hardware vintage (EMT, AMS) — son des années 80/90.", price:"~50€" },
      { name:"Valhalla Plate",         brand:"Valhalla DSP", desc:"Émulation plates analogiques — chaud, dense, vocal.", price:"~50€" },
      { name:"Valhalla Delay",         brand:"Valhalla DSP", desc:"Delay multi-mode (tape, BBD, digital) — très musical.", price:"~50€" },
      { name:"Valhalla Shimmer",       brand:"Valhalla DSP", desc:"Réverbe avec pitch-shift — ambiances cinématiques et textures.", price:"~50€" },
      { name:"FabFilter Pro-R 2",      brand:"FabFilter",  desc:"Réverbe paramétrique — contrôle précis du spectre, decay par fréquence.", price:"~199€" },
      { name:"Waves H-Reverb",         brand:"Waves",       desc:"Réverbe hybride IR+algo — flexibilité maximale.", price:"~30€" },
      { name:"Waves Manny Marroquin Reverb", brand:"Waves", desc:"Réverbe de Manny Marroquin — pré-configurée pro.", price:"~30€" },
      { name:"Lexicon PCM Native Reverb Bundle", brand:"Lexicon", desc:"Sons de reverb légendaires — standard broadcast et cinéma.", price:"~200€" },
      { name:"UAD AMS RMX16",          brand:"Universal Audio", desc:"Émulation réverbe digital AMS des années 80 — son iconique.", price:"~150€" },
      { name:"EchoBoy",                brand:"SoundToys",  desc:"Delay premium — 30+ types, saturation tape intégrée.", price:"~199€" },
      { name:"Little AlterBoy",        brand:"SoundToys",  desc:"Formant et pitch shift voix — transformations créatives.", price:"~99€" },
      { name:"Eventide H3000",         brand:"Eventide",   desc:"Modulation/delay/pitch — effets signature Eventide.", price:"~199€" },
    ],
    free: [
      { name:"Valhalla Supermassive",  brand:"Valhalla DSP", desc:"Réverbe/delay massif — Valhalla gratuit, qualité professionnelle." },
      { name:"Valhalla Space Modulator",brand:"Valhalla DSP",desc:"Flanger/chorus/réverbe — modulations créatives gratuites." },
      { name:"OrilRiver",              brand:"Denis Tihanov", desc:"Réverbe algorithmique gratuite de qualité surprenante." },
      { name:"Dragonfly Reverb",       brand:"Michael Willis", desc:"Suite de 4 réverbes gratuites (Room, Hall, Plate, Vintage)." },
      { name:"TAL-Reverb-4",           brand:"TAL Software", desc:"Réverbe vintage de qualité — son analogique gratuit." },
    ],
  },
  saturation: {
    label: "Saturation & Distorsion",
    paid: [
      { name:"FabFilter Saturn 2",     brand:"FabFilter",  desc:"Saturation multiband — 28 modes, saturation fréquence par fréquence.", price:"~179€" },
      { name:"Waves Abbey Road Saturator", brand:"Waves",  desc:"Saturation analogique Abbey Road — chaleur tape vintage.", price:"~30€" },
      { name:"Waves J37 Tape",         brand:"Waves",       desc:"Émulation magnétophone J37 — saturation tape EMI vintage.", price:"~30€" },
      { name:"SoundToys Decapitator",  brand:"SoundToys",  desc:"Saturation analogique 5 modes (A, E, N, T, Brit) — distorsion musicale.", price:"~199€" },
      { name:"SoundToys Devil-Loc",    brand:"SoundToys",  desc:"Compression/saturation destructive — drums agressifs.", price:"~99€" },
      { name:"UAD Studer A800",        brand:"Universal Audio", desc:"Émulation magnétophone multi-piste Studer — saturation tape pro.", price:"~300€" },
      { name:"UAD Ampex ATR-102",      brand:"Universal Audio", desc:"Émulation machine à bande mastering — douceur et chaleur.", price:"~150€" },
      { name:"iZotope Trash 2",        brand:"iZotope",    desc:"Distorsion creative multiband — de subtil à extrême.", price:"~99€" },
      { name:"Softube Tape",           brand:"Softube",    desc:"Saturation tape haut de gamme — émulation mécanique réaliste.", price:"~99€" },
    ],
    free: [
      { name:"Klanghelm IVGI",         brand:"Klanghelm",  desc:"Saturation analogique subtile — idéale sur chaque piste." },
      { name:"Softube Saturation Knob",brand:"Softube",    desc:"1 knob, 3 modes — saturation instantanée professionnelle." },
      { name:"TAL-DAC",                brand:"TAL Software", desc:"Bit crusher/saturation vintage — lo-fi créatif." },
      { name:"Vinyl Distortion",       brand:"iZotope (gratuit)", desc:"Émulation vinyle avec crackle et saturation." },
    ],
  },
  dynamics: {
    label: "Dynamique & Transients",
    paid: [
      { name:"FabFilter Pro-MB",       brand:"FabFilter",  desc:"Compresseur/expander multibande — précision fréquentielle totale.", price:"~179€" },
      { name:"FabFilter Pro-G",        brand:"FabFilter",  desc:"Gate/expander de référence — visualisation claire, formes variées.", price:"~179€" },
      { name:"Waves Transient Master", brand:"Waves",       desc:"Contrôle attaque/sustain en temps réel — drums et percussions.", price:"~30€" },
      { name:"Waves C6 Multiband",     brand:"Waves",       desc:"Compresseur multibande 6 bandes — maîtrise spectrale totale.", price:"~30€" },
      { name:"iZotope RX",             brand:"iZotope",    desc:"Suite de restauration audio — débruitage, décraquage, dialogue.", price:"~400€" },
      { name:"Sonnox Oxford Dynamics", brand:"Sonnox",      desc:"Compresseur/gate/limiter/expander — tout en un pro.", price:"~300€" },
      { name:"SPL Transient Designer", brand:"SPL",         desc:"Façonnage transient original — attaque/sustain indépendants.", price:"~150€" },
    ],
    free: [
      { name:"TDR Limiter 6 GE (free version)", brand:"Tokyo Dawn", desc:"Limiteur multistage de mastering — qualité commerciale." },
      { name:"Frontier",               brand:"D16 Group",  desc:"Limiteur brickwall transparent — protection crêtes gratuite." },
      { name:"MTransient",             brand:"MeldaProduction", desc:"Transient shaper précis — attaque/sustain par bande de fréquence." },
    ],
  },
  mastering: {
    label: "Mastering",
    paid: [
      { name:"iZotope Ozone 11",       brand:"iZotope",    desc:"Suite mastering tout-en-un avec IA — référence du mastering moderne.", price:"~350€" },
      { name:"FabFilter Pro-L 2",      brand:"FabFilter",  desc:"Limiteur de mastering de référence — transparent, modes multiples.", price:"~179€" },
      { name:"Waves L2 Ultramaximizer",brand:"Waves",       desc:"Limiteur légendaire — standard de l'industrie depuis 25 ans.", price:"~30€" },
      { name:"Waves MaxxVolume",       brand:"Waves",       desc:"Contrôle dynamique intelligent pour le bus master.", price:"~30€" },
      { name:"Sonnox Oxford Limiter",  brand:"Sonnox",      desc:"Limiteur mastering haute fidélité — transparent et précis.", price:"~250€" },
      { name:"Weiss DS1-MK3",          brand:"Weiss",       desc:"Compresseur/de-esser hardware mastering — référence absolue.", price:"~500€" },
      { name:"T-RackS 5 Suite",        brand:"IK Multimedia", desc:"Suite mastering complète — émulations hardware analogiques.", price:"~300€" },
    ],
    free: [
      { name:"TDR Limiter 6",          brand:"Tokyo Dawn",  desc:"Limiteur mastering multistage — qualité commerciale, 100% gratuit." },
      { name:"Youlean Loudness Meter", brand:"Youlean",    desc:"Analyse LUFS temps réel — indispensable pour le mastering streaming." },
      { name:"SPAN",                   brand:"Voxengo",    desc:"Analyseur spectral de référence — utilisé par tous les pros." },
    ],
  },
  stereo: {
    label: "Stéréo & Imaging",
    paid: [
      { name:"iZotope Imager",         brand:"iZotope",    desc:"Largeur stéréo multibande — imagerie précise par fréquence.", price:"inclus Ozone" },
      { name:"Waves S1 Stereo Imager", brand:"Waves",       desc:"Élargisseur stéréo classique — contrôle simple et efficace.", price:"~30€" },
      { name:"Waves Center",           brand:"Waves",       desc:"Séparation centre/côtés — contrôle M/S intuitif.", price:"~30€" },
      { name:"FabFilter Pro-Q 4 (M/S mode)", brand:"FabFilter", desc:"EQ en mode M/S — traitement indépendant mid et sides.", price:"~179€" },
      { name:"Brauer Motion",          brand:"Waves",       desc:"Auto-pan créatif de Michael Brauer — mouvement stéréo organique.", price:"~30€" },
    ],
    free: [
      { name:"MSED",                   brand:"Voxengo",    desc:"Encodeur/décodeur M/S — Mid-Side processing gratuit." },
      { name:"MSpectralAnalyzer",      brand:"MeldaProduction", desc:"Analyse stéréo et corrélation de phase gratuite." },
    ],
  },
  creative: {
    label: "Effets créatifs",
    paid: [
      { name:"SoundToys 5 Bundle",     brand:"SoundToys",  desc:"Suite effets créatifs complète — FilterFreak, PanMan, Tremolator, Crystallizer…", price:"~399€" },
      { name:"Waves Enigma",           brand:"Waves",       desc:"Modulateur/résonateur — textures créatives uniques.", price:"~30€" },
      { name:"Eventide H9",            brand:"Eventide",   desc:"Multi-effet signature Eventide — pitch, delay, reverb, distorsion.", price:"~399€" },
      { name:"Output Portal",          brand:"Output",     desc:"Granulaire temps réel — transformations sonores spectaculaires.", price:"~99€" },
      { name:"Arturia FX Collection",  brand:"Arturia",    desc:"Suite effets vintage hardware émulés — Bucket Brigade, Spring…", price:"~250€" },
    ],
    free: [
      { name:"TAL-Chorus-LX",          brand:"TAL Software", desc:"Émulation chorus Juno-60 — vintage analogique gratuit." },
      { name:"Valhalla Freq Echo",     brand:"Valhalla DSP", desc:"Delay fréquentiel psychédélique — effets espace créatifs." },
      { name:"MFreqShifter",           brand:"MeldaProduction", desc:"Frequency shifter créatif — effets uniques sur sons et voix." },
    ],
  },
};

export default PLUGINS_DB;
